=== TheModdedChicken/ManiaKV/ManiaKV/config-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "TTCS",
  "description": "Tippy Tap Config Schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "schemaVersion": {
      "description": "Version of Tippy Tap schema",
      "type": "string",
      "examples": [ "1.0" ]
    },
    "window": {
      "description": "Window settings",
      "type": "object",
      "properties": {
        "width": {
          "description": "Window width in pixels",
          "type": "number"
        },
        "height": {
          "description": "Window height in pixels",
          "type": "number"
        },
        "alwaysOntop": {
          "description": "Set window to always stay ontop of other windows",
          "type": "boolean"
        },
        "transparent": {
          "description": "Set window to be transparent",
          "type": "boolean"
        },
        "undecorated": {
          "description": "Disable window decorations (Frame and Buttons)",
          "type": "boolean"
        }
      }
    },
    "stages": {
      "description": "Key setups able to be used",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "ID of this key setup",
            "type": "string",
            "examples": [ "2k", "4k", "5k", "6k", "7k", "8k", "9k", "10k" ]
          },
          "characters": {
            "description": "Characters to use (Displayed in the order listed)",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "keys": {
            "description": "Keys able to be used with this setup",
            "type": "array",
            "items": {
              "type": "string",
              "examples": [

              ]
            }
          },
          "shortcut": {
            "description": "Keyboard shortcut used to load this setup. (Ctrl + Shift + 1)",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "background": {
            "description": "Location of background image",
            "type": "string"
          },
          "table": {
            "description": "Location of table image",
            "type": "string"
          }
        },
        "required": [ "id" ]
      }
    },
    "characters": {
      "type": "array",
      "description": "Characters able to be used",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "description": "ID of character",
            "type": "string"
          },
          "body": {
            "description": "Location of character body image. (File location should NOT start with './' or '/')",
            "type": "string"
          },
          "instrument": {
            "description": "Location of instrument image. (File location should NOT start with './' or '/')",
            "type": "string"
          },
          "keys": {
            "description": "Amount of keys able to be used with this character",
            "type": "number",
            "examples": [ 2, 4 ]
          },
          "leftHand": {
            "description": "Images pertaining to the character's left hand. (File locations should NOT start with './' or '/')",
            "type": "object"
          },
          "rightHand": {
            "description": "Images pertaining to the character's right hand. (File locations should NOT start with './' or '/')",
            "type": "object"
          }
        },
        "required": [ "id", "keys" ]
      }
    }
  }
}

=== TheModdedChicken/ManiaKV/ManiaKV/userdata/config.json
{
  "$schema": "https://raw.githubusercontent.com/TheModdedChicken/ManiaKV/main/ManiaKV/config-schema.json",
  "schemaVersion": "1.0",
  "window" : {
    "windowWidth": 594,
    "windowHeight": 334
  },
  "stages": [
    {
      "id": "2k",
      "keys": [ "A", "S" ],
      "characters": [ "bongoCat2k" ],
      "hotkey": 2,
      "background": "background.png",
      "table": "table.png"
    },
    {
      "id": "3k",
      "keys": [ "A", "S", "D" ],
      "characters": [ "bongoCat4k" ],
      "hotkey": 3,
      "background": "background.png",
      "table": "table.png"
    },
    {
      "id": "4k",
      "keys": [ "A", "S", "SEMI_COLON", "SINGLE_QUOTE" ],
      "characters": [ "bongoCat4k" ],
      "hotkey": 4,
      "background": "background.png",
      "table": "table.png"
    },
    {
      "id": "6k",
      "keys": [ "A", "S", "D", "L", "SEMI_COLON", "SINGLE_QUOTE" ],
      "characters": [ "bongoCat4k", "bongoCat2k" ],
      "hotkey": 6,
      "background": "background.png",
      "table": "table.png"
    },
    {
      "id": "7k",
      "keys": [ "A", "S", "D", "SPACE", "L", "SEMI_COLON", "SINGLE_QUOTE" ],
      "characters": [ "bongoCat4k", "bongoCat4k" ],
      "hotkey": 7,
      "background": "background.png",
      "table": "table.png"
    },
    {
      "id": "8k",
      "keys": [ "A", "S", "D", "F", "K", "L", "SEMI_COLON", "SINGLE_QUOTE" ],
      "characters": [ "bongoCat4k", "bongoCat4k" ],
      "hotkey": 8,
      "background": "background.png",
      "table": "table.png"
    }
  ],
  "characters": [
    {
      "id": "bongoCat4k",
      "body": "bongoCat4k/body.png",
      "instrument": "bongoCat4k/instrument.png",
      "keys": 4,
      "textures": {
        "leftIdle": "bongoCat4k/leftPaw_idle.png",
        "rightIdle": "bongoCat4k/rightPaw_idle.png",
        "key1": "bongoCat4k/leftPaw_key1.png",
        "key2": "bongoCat4k/leftPaw_key2.png",
        "key1-2": "bongoCat4k/leftPaw_key1-2.png",
        "key3": "bongoCat4k/rightPaw_key3.png",
        "key4": "bongoCat4k/rightPaw_key4.png",
        "key3-4": "bongoCat4k/rightPaw_key3-4.png"
      }
    },
    {
      "id": "bongoCat2k",
      "body": "bongoCat2k/body.png",
      "instrument": "bongoCat2k/instrument.png",
      "keys": 2,
      "textures": {
        "leftIdle": "bongoCat2k/leftPaw_idle.png",
        "rightIdle": "bongoCat2k/rightPaw_idle.png",
        "key1": "bongoCat2k/leftPaw_key1.png",
        "key2": "bongoCat2k/rightPaw_key2.png"
      }
    }
  ]
}
